{
  imports = [
    ./boot.nix
    ./nix.nix
    ./networking.nix
    ./bluetooth.nix
    ./time.nix
    ./locales.nix
    ./users.nix
    ./hosts.nix
    ./pipewire.nix
    ./security.nix
    ./zswap.nix
    ./zapret.nix
    ./fonts.nix
    ./gpu-screen-recorder.nix
    ./shells.nix
  ];
}
